### ISSUE TITLE
Status Update?

### ISSUE THREAD

**Issue by mackermedia** [mazurio/fit-for-reddit-ios#1]
Saw this repo via the reddit "Upvoted Weekly" email digest and thought it sounds like a great idea. 
The README was updated saying this was submitted to the app store over a month ago. 

Is there anything I can do to help out on this effort?

**Comment by haabaato** [comment]
:+1: I'm also waiting to contribute. :)

**Comment by mazurio** [comment]
Hi guys,

I had no idea it was in `Upvoted Weekly`, I will take a look. I have just updated the repo @haabaato @mackermedia .. :)
