### ISSUE TITLE
Add rest timer for strength exercises.  

### ISSUE THREAD

**Issue by aaron832** [mazurio/fit-for-reddit-ios#17]
Before timers were removed for exercises that did not need them,  I regularly used the timer to time rest periods between exercises.  It would be really useful to know when to start the next set with this app.

**Comment by mazurio** [comment]
Hi @aaron832 - I am aware of that. I am currently working on proper rest timers for both Android and iOS. Hopefully they are released very soon!

Thanks,
Damian

**Comment by mazurio** [comment]
Hi @aaron832 - this is now done on master. I am waiting for Apple to review the submission. :-)
