### ISSUE TITLE
App turns off music/podcast when switching exercises

### ISSUE THREAD

**Issue by RobertFiorentino** [mazurio/fit-for-reddit-ios#18]
I'd assume many people listen to music or podcasts while working out, so this issue is a bit of a dealbreaker for the app.

**Comment by mazurio** [comment]
Hi @RobertFiorentino - make sure to update to 1.4.3 which already fixes this bug https://itunes.apple.com/us/app/bodyweight-fitness/id1018863605

**Comment by RobertFiorentino** [comment]
Ah great. Thanks!
