### ISSUE TITLE
bodyline drills rest

### ISSUE THREAD

**Issue by paskal** [mazurio/fit-for-reddit-ios#35]
Rest between bodyline drills [note](https://www.reddit.com/r/bodyweightfitness/wiki/kb/recommended_routine):
> Do NOT Rest between the bodyline drills. Just move to the next one with minimal rest.
I guess the app should change default behavior to reflect this important note - settings by default right now add 60 seconds rest between everything including these.

**Comment by paskal** [comment]
Last version still posses the same issue.

**Comment by paskal** [comment]
I found it to be optional. However, it might be appropriate turning it off by default.

**Comment by bamse16** [comment]
Yeah, I think you can tap on "pause" and it will stop the rest time.

**Comment by paskal** [comment]
I've meant following:
![timers](https://user-images.githubusercontent.com/712534/34638360-f6826740-f2da-11e7-8bd8-dfd450e95a80.jpg)
If I recall correctly, timer for bodyline drills was ON by default.
