### ISSUE TITLE
progress on advanced progressions does not show up in workout log.

### ISSUE THREAD

**Issue by kurniad001** [mazurio/fit-for-reddit-ios#9]
Doing advanced progressions like diamond push-ups or horiZontal rows does not show on the workout log as completed. The workout log only reads from the beginning workout. 

Additionally if we can see all competed workouts and reps on one page instead of clicking each one to see where we are that would be amazing. 

Thank you, really loving this workout app btw.

**Comment by mazurio** [comment]
Thanks for letting me know - I will fix this with the next release. I am planning to add the sets/reps graphs and views in the progress view too so we don't have to click 👍

**Comment by mazurio** [comment]
Fixed in 1.2.0
